### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by Zirak** [JavaScriptRoom/oojs#2]
What're the style guidelines? Specifically about bracket placement, since it appears to be in conflict (a quick look through the files shows that).

**Comment by ryankinal** [comment]
I meant to convert everything to the Popular Style, but things ended up in my style because I'm lazy.

So... I guess it's the WTFSG (Do what the fuck you want style guide).

**Comment by SomeKittens** [comment]
AirBnB has a neat style guide here: https://github.com/airbnb/javascript  (It's also good for teaching, as it points out common gotchas)
